CREATE TABLE Pagination (
    pageId SERIAL PRIMARY KEY,
    pageNumber INT NOT NULL,
    pageSize INT NOT NULL,
    totalItems INT NOT NULL,
    totalPages INT NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);